spring:
  application:
    name: back
  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/maum_on_dev}
    username: ${DEV_DB_USERNAME:maum_on}
    password: ${DEV_DB_PASSWORD:maum_on}
  jpa:
    hibernate:
      ddl-auto: create-drop
gemini:
  api:
    key: ${GOOGLE_API_KEY:test_key_dummy}