spring:
  application:
    name: back
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  data:
    redis:
      host: ${PROD_REDIS_URL}
      password: ${PROD_REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
custom:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    refresh-token-cookie-secure: ${JWT_REFRESH_TOKEN_COOKIE_SECURE:true}
    refresh-token-cookie-same-site: ${JWT_REFRESH_TOKEN_COOKIE_SAME_SITE:None}
